# Generated by Django 5.2.7 on 2025-10-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Низкий"), ("medium", "Средний"), ("high", "Высокий")],
                max_length=10,
                verbose_name="Приоритет",
            ),
        ),
    ]
