# Generated by Django 5.2.7 on 2025-10-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Задача выполнена"),
        ),
    ]
